/*
	Alg1.cpp
*/

#ifdef __CPLUSPLUS
extern "C" {
#endif

/*
	DO NOT EDIT THIS FILE. ALGORITHM 1 IS NEVER USED IN KOM FILES.
*/
#include <Windows.h>
#include <string>

unsigned char* Alg1_Unpacker(std::string FileName, unsigned char* FileData, std::string DestPath) {
	//This seems to not be Used.
	return NULL;
}

unsigned char* Alg1_Packer(unsigned char* FileData) {
	//This seems to not be Used.
	return NULL;
}

#ifdef __CPLUSPLUS
}
#endif
