/*
	Alg1.cpp
*/

#ifdef __CPLUSPLUS
extern "C" {
#endif

/*
	DO NOT EDIT THIS FILE. ALGORITHM 1 IS NEVER USED IN KOM FILES.
*/
#include <Windows.h>
#include <string>

char* Alg1_Unpacker(std::string FileName, char* FileData, std::string DestPath) {
	//This Cannot be Used. So, lets Return the Pointer Instead.
	return FileData;
}

char* Alg1_Packer(char* FileData) {
	//This Cannot be Used. So, lets Return the Pointer Instead.
	return FileData;
}

#ifdef __CPLUSPLUS
}
#endif
