/*
	Alg1.hpp
*/

/*
	DO NOT EDIT THIS FILE. ALGORITHM 1 IS NEVER USED IN KOM FILES.
*/
#include <Windows.h>
#include <string>

namespace Alg1
{
	inline int Unpacker(std::string FileName)
	{
		return 0;
	}

	inline int Packer(std::string FileName)
	{
		return 0;
	}
};
