/*
	Alg1.cpp
*/

#ifdef __CPLUSPLUS
extern "C" {
#endif

/*
	DO NOT EDIT THIS FILE. ALGORITHM 1 IS NEVER USED IN KOM FILES.
*/
#include <Windows.h>
#include <string>

int Alg1_Unpacker(std::string FileName) {
	//This Cannot be Used. So, lets Return the Pointer Instead.
	return 0;
}

int Alg1_Packer(std::string FileName) {
	return 0;
}

#ifdef __CPLUSPLUS
}
#endif
