// Copyright (c) 2014-2018, Els_kom org.
// https://github.com/Elskom/
// All rights reserved.
// license: MIT, see LICENSE for more details.

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.settingsTmr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.packingTmr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.unpackingTmr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.testModsTmr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.launcherTmr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.contextMenuStrip1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.packToolStripMenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.unpackToolStripMenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.testModsToolStripMenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.launcherToolStripMenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.exitToolStripMenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP002:Dispose member.", Justification = "Disposed when control is disposed of.", Scope = "member", Target = "~F:Els_kom_Core.Controls.MainControl.toolStripMenuSep1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.LoadControl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.WndProc(System.Windows.Forms.Message@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.Command4_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.Command5_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.LauncherToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.TestModsToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.TestMods2(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.Launcher(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Fixing this by using a using block on this would make the program close.", Scope = "member", Target = "~M:Els_kom_Core.Controls.MainControl.CheckSettings(System.Object,System.EventArgs)")]
